spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to dummy bank cards related QA APIs "
  contactDetails:
    name: "Cherry - QA Lead"
    email: "cherry@dummybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267