build:
  version: "1.0"

accounts:
  message: "Welcome to dummy bank accounts related prod APIs "
  contactDetails:
    name: "John Doe - Product owner"
    email: "john_prod@dummybank.com"
  onCallSupport:
    - (555) 555-1231
    - (555) 523-1341