build:
  version: "1.0"

cards:
  message: "Welcome to dummy bank cards related prod APIs "
  contactDetails:
    name: "Peter Doe - Product Owner"
    email: "peter@dummybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721