build:
  version: "3.0"

loans:
  message: "Welcome to dummy bank loans related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@dummybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934