build:
  version: "1.0"

loans:
  message: "Welcome to dummy loans related prod APIs "
  contactDetails:
    name: "Vero - Product Owner"
    email: "vero@dummybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956